### ISSUE TITLE
Database doesn't persist on restart

### ISSUE THREAD

**Issue by kunumigab** [Vvveb/docker#2]
Hello! I'm testing your project, on [coolify](https://github.com/coollabsio/coolify)

First i tested with sqllite, but then i move to mariadb... env/volumes works, but every time i restart the stack it reset.

Is there something that i'm doing wrong?

This is my compose:

```
services:
  vvveb:
    image: 'vvveb/vvvebcms:php8.3-fpm-alpine'
    environment:
      - SERVICE_FQDN_VVVEB
      - DB_HOST=mariadb
      - DB_DATABASE=${MYSQL_DB:-vvveb_db}
      - DB_USER=${SERVICE_USER_VVVEB}
      - DB_PASSWORD=${SERVICE_PASSWORD_VVVEB}
      - DB_ENGINE=mysqli
    volumes:
      - "vvveb_data:/var/www/vvveb/"
      - "vvveb_mariadb_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOTMARIADB}
      - MARIADB_DATABASE=${MYSQL_DB:-vvveb_db}
      - MARIADB_USER=${SERVICE_USER_VVVEB}
      - MARIADB_PASSWORD=${SERVICE_PASSWORD_VVVEB}
    volumes:
      - "vvveb_mariadb_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 20s
      retries: 10
volumes:
  vvveb_data:
  mariadb_data:
```
